server:
  port: 9092

# Maximum number of concurrent screenshot requests
screenshot:
  max-concurrent-requests: 10

cloudflare:
  r2:
    access-key:
    secret-key:
    bucket-name:
    endpoint:
    region: auto
    domain:


# site domain，填写域名或者IP+端口
domain: http://127.0.0.1:9092