server:
  port: 9092

# Maximum number of concurrent screenshot requests
screenshot:
  max-concurrent-requests: 10

cloudflare:
  r2:
    access-key:
    secret-key:
    bucket-name:
    endpoint: https://xxxxxx.r2.cloudflarestorage.com
    region: auto
    domain: pub-xxxxxx.r2.dev


# site domain，填写域名或者IP+端口
domain: http://127.0.0.1:9092